### ISSUE TITLE
Clicking 'Join' to a shift with empty spaces does nothing

### ISSUE THREAD

**Issue by reapsta** [goingnowhere/volunteers-nowhere#27]
Hi there, 

Looking at cribbing this to re-use in the Australian burn community. After getting it working (I am not at all familiar with meteor), I noticed that the Join button to join a shift doesn't work, and leaves this in the console error log :

Uncaught ReferenceError: applyCall is not defined
    at onClickSignup (SignupShiftRow.jsx:17:36)
    at onClick (SignupShiftButtons.jsx:31:24)
    at HTMLUnknownElement.callCallback (modules.js?hash=cb6ee5a017f7447d7d5828002eaf998062823674:44398:14)
    at Object.invokeGuardedCallbackDev (modules.js?hash=cb6ee5a017f7447d7d5828002eaf998062823674:44447:16)
    at invokeGuardedCallback (modules.js?hash=cb6ee5a017f7447d7d5828002eaf998062823674:44502:31)
    at invokeGuardedCallbackAndCatchFirstError (modules.js?hash=cb6ee5a017f7447d7d5828002eaf998062823674:44516:25)
    at executeDispatch (modules.js?hash=cb6ee5a017f7447d7d5828002eaf998062823674:44599:3)
    at executeDispatchesInOrder (modules.js?hash=cb6ee5a017f7447d7d5828002eaf998062823674:44621:7)
    at executeDispatchesAndRelease (modules.js?hash=cb6ee5a017f7447d7d5828002eaf998062823674:47488:5)
    at executeDispatchesAndReleaseTopLevel (modules.js?hash=cb6ee5a017f7447d7d5828002eaf998062823674:47497:10)

I am not sure if I have missed a dependency or something, or this functionality isn't implemented yet?

**Comment by piemonkey** [comment]
Ah, thanks for spotting this, it looks like I broke it while changing something for event-time, when people applying this way is rare as they're more likely to go to NoInfo in person. Ironically the change was to better support them signing up at NoInfo. I didn't see it as my eslint config in my editor was broken.

I've fixed it now on master.

Feel free to send me an email if you're thinking to use it, I'd be very happy to help support you using it, as it's always better to have your code used.
